# Generated by Django 5.2 on 2025-04-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_at',
            field=models.DateField(null=True),
        ),
    ]
